### ISSUE TITLE
i can't play tetris

### ISSUE THREAD

**Issue by omaromarver** [seraphim2022/MAS_learn_together#1]
![error](https://github.com/seraphim2022/MAS_learn_together/assets/42177816/b6d3a79b-ff4d-4e43-a7d1-9bc2cb960806)
when i try to play tetris solo or co-op i got this error.
is there a way to fix it?

**Comment by seraphim2022** [comment]
Did you extract it? Also if you did extract it did you move the entire Learn together folder into the submods directory I myself have made the mistake of just putting it in the game directory and get an error like this also sorry for the late reply it has been awhile since I have been on github

**Comment by omaromarver** [comment]
> Did you extract it? Also if you did extract it did you move the entire Learn together folder into the submods directory I myself have made the mistake of just putting it in the game directory and get an error like this also sorry for the late reply it has been awhile since I have been on github

yes i did, but i still got this error.
btw, my version is 0.12.9

**Comment by seraphim2022** [comment]
Can you scroll down and take a screen shot of the full trace back

**Comment by seraphim2022** [comment]
Actually looking at it I may have found the issue when the file is compressed I name it it looks like you have moved the entire file over take the learn together folder out of the Mas learn together 1.0.4 folder when you are done you should only have a folder named learn together in the submods directory let me know if this fixes it
